// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5QDRpkdvheHSLfh8hbOYucQYjuI29u94',
    appId: '1:864457125511:web:f0c6585bde845503129222',
    messagingSenderId: '864457125511',
    projectId: 'smart-home-app-c8e01',
    authDomain: 'smart-home-app-c8e01.firebaseapp.com',
    databaseURL: 'https://smart-home-app-c8e01-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-app-c8e01.appspot.com',
    measurementId: 'G-5SNKVFE8YN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbZQCv8zS2oPIFwU8BeHAACiQEz1tHeSM',
    appId: '1:864457125511:android:fdc256cec4c1fb2f129222',
    messagingSenderId: '864457125511',
    projectId: 'smart-home-app-c8e01',
    databaseURL: 'https://smart-home-app-c8e01-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-app-c8e01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYiJVEo-D_uP9r2PahvKZPURNRB_58Jpc',
    appId: '1:864457125511:ios:fb45eb30acba7887129222',
    messagingSenderId: '864457125511',
    projectId: 'smart-home-app-c8e01',
    databaseURL: 'https://smart-home-app-c8e01-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-app-c8e01.appspot.com',
    iosBundleId: 'com.example.smartHome',
  );
}
